name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fix torch for pyinstaller
      run: |
        dir
        cd ..
        dir
        cd ..
        dir
        cd ..
        dir
        
    - name: UploadArtifacts
      uses: actions/upload-artifact@v4
      with:
          name: Distributive
          path: |
              task5/bin/
              task5/lib/
