name: Windows build

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies in venv
      run: |
        python -m venv venv
        cmd /C venv\Scripts\activate.bat
        dir
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        replace extra\windows-build\_script.py venv\Lib\site-packages\torch\jit\
        cd venv\Lib\site-packages
        dir
    
    - name: Fix torch for pyinstaller
      run: |
        dir
        cd ..
        dir
        cd ..
        dir
        cd ..
        dir
        
    - name: UploadArtifacts
      uses: actions/upload-artifact@v3
      with:
          name: Distributive
          path: |
              ./
